var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/architecture-overview/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1g_o59n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0l32r_s.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-0c8y-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_0y71rcy._.js")
R.c("server/chunks/ssr/node_modules_tailwind-merge_dist_bundle-mjs_mjs_1lgrlpt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_architecture-overview_page_actions_0fc29ha.js")
R.m(43297)
module.exports=R.m(43297).exports
